# Generated by Django 5.0.6 on 2024-05-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
